
import { Asset } from "../types/asset-types";

// Commodities
export const energyCommodities: Asset[] = [
  {
    symbol: 'CL=F',
    name: 'Crude Oil WTI',
    type: 'commodity',
    currentPrice: 81.45,
    priceChange: 1.32,
    priceChangePercent: 1.65,
    market: 'NYMEX',
  },
  {
    symbol: 'BZ=F',
    name: 'Brent Crude Oil',
    type: 'commodity',
    currentPrice: 85.32,
    priceChange: 1.24,
    priceChangePercent: 1.47,
    market: 'NYMEX',
  },
  {
    symbol: 'NG=F',
    name: 'Natural Gas',
    type: 'commodity',
    currentPrice: 1.81,
    priceChange: 0.04,
    priceChangePercent: 2.26,
    market: 'NYMEX',
  },
];

export const metalCommodities: Asset[] = [
  {
    symbol: 'GC=F',
    name: 'Gold',
    type: 'commodity',
    currentPrice: 2312.40,
    priceChange: 8.70,
    priceChangePercent: 0.38,
    market: 'COMEX',
  },
  {
    symbol: 'SI=F',
    name: 'Silver',
    type: 'commodity',
    currentPrice: 27.54,
    priceChange: 0.32,
    priceChangePercent: 1.18,
    market: 'COMEX',
  },
  {
    symbol: 'HG=F',
    name: 'Copper',
    type: 'commodity',
    currentPrice: 4.52,
    priceChange: 0.05,
    priceChangePercent: 1.12,
    market: 'COMEX',
  },
  {
    symbol: 'PL=F',
    name: 'Platinum',
    type: 'commodity',
    currentPrice: 943.70,
    priceChange: 5.80,
    priceChangePercent: 0.62,
    market: 'COMEX',
  },
  {
    symbol: 'PA=F',
    name: 'Palladium',
    type: 'commodity',
    currentPrice: 952.30,
    priceChange: 7.40,
    priceChangePercent: 0.78,
    market: 'COMEX',
  },
];

export const agriculturalCommodities: Asset[] = [
  {
    symbol: 'ZC=F',
    name: 'Corn',
    type: 'commodity',
    currentPrice: 448.25,
    priceChange: 3.75,
    priceChangePercent: 0.84,
    market: 'NYMEX',
  },
  {
    symbol: 'ZW=F',
    name: 'Wheat',
    type: 'commodity',
    currentPrice: 567.50,
    priceChange: 5.25,
    priceChangePercent: 0.93,
    market: 'NYMEX',
  },
  {
    symbol: 'ZS=F',
    name: 'Soybeans',
    type: 'commodity',
    currentPrice: 1187.25,
    priceChange: 8.50,
    priceChangePercent: 0.72,
    market: 'NYMEX',
  },
  {
    symbol: 'KC=F',
    name: 'Coffee',
    type: 'commodity',
    currentPrice: 192.35,
    priceChange: 2.15,
    priceChangePercent: 1.13,
    market: 'NYMEX',
  },
  {
    symbol: 'SB=F',
    name: 'Sugar',
    type: 'commodity',
    currentPrice: 18.42,
    priceChange: 0.18,
    priceChangePercent: 0.99,
    market: 'NYMEX',
  },
  {
    symbol: 'CC=F',
    name: 'Cocoa',
    type: 'commodity',
    currentPrice: 10210.00,
    priceChange: 145.00,
    priceChangePercent: 1.44,
    market: 'NYMEX',
  },
  {
    symbol: 'CT=F',
    name: 'Cotton',
    type: 'commodity',
    currentPrice: 77.65,
    priceChange: 0.58,
    priceChangePercent: 0.75,
    market: 'NYMEX',
  },
];
