
import { Asset } from "../types/asset-types";

// US Retail and Consumer Stocks
export const consumerStocks: Asset[] = [
  {
    symbol: 'WMT',
    name: 'Walmart Inc.',
    type: 'stock',
    currentPrice: 71.84,
    priceChange: 0.52,
    priceChangePercent: 0.73,
    market: 'NYSE',
  },
  {
    symbol: 'HD',
    name: 'Home Depot Inc.',
    type: 'stock',
    currentPrice: 345.27,
    priceChange: -2.18,
    priceChangePercent: -0.63,
    market: 'NYSE',
  },
  {
    symbol: 'PG',
    name: 'Procter & Gamble Co.',
    type: 'stock',
    currentPrice: 169.02,
    priceChange: 0.87,
    priceChangePercent: 0.52,
    market: 'NYSE',
  },
  {
    symbol: 'KO',
    name: 'The Coca-Cola Company',
    type: 'stock',
    currentPrice: 62.54,
    priceChange: 0.32,
    priceChangePercent: 0.51,
    market: 'NYSE',
  },
  {
    symbol: 'PEP',
    name: 'PepsiCo, Inc.',
    type: 'stock',
    currentPrice: 174.83,
    priceChange: 0.57,
    priceChangePercent: 0.33,
    market: 'NYSE',
  },
  {
    symbol: 'DIS',
    name: 'The Walt Disney Company',
    type: 'stock',
    currentPrice: 102.48,
    priceChange: 1.36,
    priceChangePercent: 1.34,
    market: 'NYSE',
  },
  {
    symbol: 'NKE',
    name: 'NIKE, Inc.',
    type: 'stock',
    currentPrice: 93.76,
    priceChange: 0.45,
    priceChangePercent: 0.48,
    market: 'NYSE',
  },
  {
    symbol: 'SBUX',
    name: 'Starbucks Corporation',
    type: 'stock',
    currentPrice: 78.52,
    priceChange: -0.67,
    priceChangePercent: -0.85,
    market: 'NYSE',
  },
  {
    symbol: 'MCD',
    name: 'McDonald\'s Corporation',
    type: 'stock',
    currentPrice: 284.24,
    priceChange: 1.87,
    priceChangePercent: 0.66,
    market: 'NYSE',
  },
  {
    symbol: 'COST',
    name: 'Costco Wholesale Corporation',
    type: 'stock',
    currentPrice: 867.32,
    priceChange: 5.24,
    priceChangePercent: 0.61,
    market: 'NYSE',
  },
];
