
import { Asset } from "../types/asset-types";

// Cryptocurrencies
export const cryptocurrencies: Asset[] = [
  {
    symbol: 'BTC/USD',
    name: 'Bitcoin / US Dollar',
    type: 'crypto',
    currentPrice: 66289.45,
    priceChange: 1243.67,
    priceChangePercent: 1.91,
    market: 'Various Exchanges',
  },
  {
    symbol: 'ETH/USD',
    name: 'Ethereum / US Dollar',
    type: 'crypto',
    currentPrice: 3124.56,
    priceChange: 87.24,
    priceChangePercent: 2.87,
    market: 'Various Exchanges',
  },
  {
    symbol: 'BNB/USD',
    name: 'Binance Coin / US Dollar',
    type: 'crypto',
    currentPrice: 574.32,
    priceChange: 12.76,
    priceChangePercent: 2.27,
    market: 'Various Exchanges',
  },
  {
    symbol: 'SOL/USD',
    name: 'Solana / US Dollar',
    type: 'crypto',
    currentPrice: 146.32,
    priceChange: 5.17,
    priceChangePercent: 3.66,
    market: 'Various Exchanges',
  },
  {
    symbol: 'XRP/USD',
    name: 'Ripple / US Dollar',
    type: 'crypto',
    currentPrice: 0.5243,
    priceChange: 0.0123,
    priceChangePercent: 2.40,
    market: 'Various Exchanges',
  },
  {
    symbol: 'ADA/USD',
    name: 'Cardano / US Dollar',
    type: 'crypto',
    currentPrice: 0.4576,
    priceChange: 0.0087,
    priceChangePercent: 1.94,
    market: 'Various Exchanges',
  },
  {
    symbol: 'DOGE/USD',
    name: 'Dogecoin / US Dollar',
    type: 'crypto',
    currentPrice: 0.1321,
    priceChange: 0.0032,
    priceChangePercent: 2.48,
    market: 'Various Exchanges',
  },
  {
    symbol: 'AVAX/USD',
    name: 'Avalanche / US Dollar',
    type: 'crypto',
    currentPrice: 35.76,
    priceChange: 1.23,
    priceChangePercent: 3.56,
    market: 'Various Exchanges',
  },
  {
    symbol: 'DOT/USD',
    name: 'Polkadot / US Dollar',
    type: 'crypto',
    currentPrice: 7.32,
    priceChange: 0.21,
    priceChangePercent: 2.95,
    market: 'Various Exchanges',
  },
  {
    symbol: 'LINK/USD',
    name: 'Chainlink / US Dollar',
    type: 'crypto',
    currentPrice: 14.54,
    priceChange: 0.43,
    priceChangePercent: 3.05,
    market: 'Various Exchanges',
  },
  {
    symbol: 'MATIC/USD',
    name: 'Polygon / US Dollar',
    type: 'crypto',
    currentPrice: 0.7243,
    priceChange: 0.0232,
    priceChangePercent: 3.31,
    market: 'Various Exchanges',
  },
  {
    symbol: 'UNI/USD',
    name: 'Uniswap / US Dollar',
    type: 'crypto',
    currentPrice: 7.82,
    priceChange: 0.23,
    priceChangePercent: 3.03,
    market: 'Various Exchanges',
  },
  {
    symbol: 'SHIB/USD',
    name: 'Shiba Inu / US Dollar',
    type: 'crypto',
    currentPrice: 0.0000215,
    priceChange: 0.0000008,
    priceChangePercent: 3.87,
    market: 'Various Exchanges',
  },
  {
    symbol: 'LTC/USD',
    name: 'Litecoin / US Dollar',
    type: 'crypto',
    currentPrice: 78.45,
    priceChange: 1.87,
    priceChangePercent: 2.44,
    market: 'Various Exchanges',
  },
  {
    symbol: 'XLM/USD',
    name: 'Stellar / US Dollar',
    type: 'crypto',
    currentPrice: 0.1187,
    priceChange: 0.0032,
    priceChangePercent: 2.77,
    market: 'Various Exchanges',
  },
];
