
import { Asset } from "../types/asset-types";

// US Financial Stocks
export const financialStocks: Asset[] = [
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    type: 'stock',
    currentPrice: 198.46,
    priceChange: -1.24,
    priceChangePercent: -0.62,
    market: 'NYSE',
  },
  {
    symbol: 'BAC',
    name: 'Bank of America Corporation',
    type: 'stock',
    currentPrice: 37.82,
    priceChange: 0.31,
    priceChangePercent: 0.83,
    market: 'NYSE',
  },
  {
    symbol: 'WFC',
    name: 'Wells Fargo & Company',
    type: 'stock',
    currentPrice: 57.45,
    priceChange: 0.87,
    priceChangePercent: 1.54,
    market: 'NYSE',
  },
  {
    symbol: 'C',
    name: 'Citigroup Inc.',
    type: 'stock',
    currentPrice: 61.25,
    priceChange: -0.45,
    priceChangePercent: -0.73,
    market: 'NYSE',
  },
  {
    symbol: 'GS',
    name: 'The Goldman Sachs Group, Inc.',
    type: 'stock',
    currentPrice: 446.92,
    priceChange: 3.76,
    priceChangePercent: 0.85,
    market: 'NYSE',
  },
  {
    symbol: 'MS',
    name: 'Morgan Stanley',
    type: 'stock',
    currentPrice: 97.25,
    priceChange: 0.54,
    priceChangePercent: 0.56,
    market: 'NYSE',
  },
  {
    symbol: 'V',
    name: 'Visa Inc.',
    type: 'stock',
    currentPrice: 273.84,
    priceChange: 1.97,
    priceChangePercent: 0.72,
    market: 'NYSE',
  },
  {
    symbol: 'MA',
    name: 'Mastercard Incorporated',
    type: 'stock',
    currentPrice: 457.92,
    priceChange: 2.41,
    priceChangePercent: 0.53,
    market: 'NYSE',
  },
  {
    symbol: 'AXP',
    name: 'American Express Company',
    type: 'stock',
    currentPrice: 228.64,
    priceChange: 1.23,
    priceChangePercent: 0.54,
    market: 'NYSE',
  },
];
