
import { Asset } from "../types/asset-types";

// Forex Pairs (Major, Minor, si exotic cu RON)
export const majorForexPairs: Asset[] = [
  {
    symbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    type: 'forex',
    currentPrice: 1.0842,
    priceChange: -0.0023,
    priceChangePercent: -0.21,
    market: 'OTC',
  },
  {
    symbol: 'GBP/USD',
    name: 'British Pound / US Dollar',
    type: 'forex',
    currentPrice: 1.2547,
    priceChange: 0.0031,
    priceChangePercent: 0.25,
    market: 'OTC',
  },
  {
    symbol: 'USD/JPY',
    name: 'US Dollar / Japanese Yen',
    type: 'forex',
    currentPrice: 153.26,
    priceChange: 0.42,
    priceChangePercent: 0.27,
    market: 'OTC',
  },
  {
    symbol: 'USD/CHF',
    name: 'US Dollar / Swiss Franc',
    type: 'forex',
    currentPrice: 0.8978,
    priceChange: -0.0012,
    priceChangePercent: -0.13,
    market: 'OTC',
  },
  {
    symbol: 'AUD/USD',
    name: 'Australian Dollar / US Dollar',
    type: 'forex',
    currentPrice: 0.6624,
    priceChange: 0.0014,
    priceChangePercent: 0.21,
    market: 'OTC',
  },
  {
    symbol: 'USD/CAD',
    name: 'US Dollar / Canadian Dollar',
    type: 'forex',
    currentPrice: 1.3642,
    priceChange: -0.0027,
    priceChangePercent: -0.20,
    market: 'OTC',
  },
  {
    symbol: 'NZD/USD',
    name: 'New Zealand Dollar / US Dollar',
    type: 'forex',
    currentPrice: 0.6032,
    priceChange: 0.0008,
    priceChangePercent: 0.13,
    market: 'OTC',
  },
];

// Minor si cross forex pairs
export const minorForexPairs: Asset[] = [
  {
    symbol: 'EUR/GBP',
    name: 'Euro / British Pound',
    type: 'forex',
    currentPrice: 0.8642,
    priceChange: -0.0018,
    priceChangePercent: -0.21,
    market: 'OTC',
  },
  {
    symbol: 'EUR/JPY',
    name: 'Euro / Japanese Yen',
    type: 'forex',
    currentPrice: 166.18,
    priceChange: 0.23,
    priceChangePercent: 0.14,
    market: 'OTC',
  },
  {
    symbol: 'EUR/CHF',
    name: 'Euro / Swiss Franc',
    type: 'forex',
    currentPrice: 0.9734,
    priceChange: -0.0021,
    priceChangePercent: -0.22,
    market: 'OTC',
  },
  {
    symbol: 'GBP/JPY',
    name: 'British Pound / Japanese Yen',
    type: 'forex',
    currentPrice: 192.31,
    priceChange: 0.54,
    priceChangePercent: 0.28,
    market: 'OTC',
  },
  {
    symbol: 'CHF/JPY',
    name: 'Swiss Franc / Japanese Yen',
    type: 'forex',
    currentPrice: 170.73,
    priceChange: 0.38,
    priceChangePercent: 0.22,
    market: 'OTC',
  },
  {
    symbol: 'EUR/AUD',
    name: 'Euro / Australian Dollar',
    type: 'forex',
    currentPrice: 1.6367,
    priceChange: -0.0028,
    priceChangePercent: -0.17,
    market: 'OTC',
  },
  {
    symbol: 'GBP/AUD',
    name: 'British Pound / Australian Dollar',
    type: 'forex',
    currentPrice: 1.8941,
    priceChange: 0.0034,
    priceChangePercent: 0.18,
    market: 'OTC',
  },
  {
    symbol: 'AUD/JPY',
    name: 'Australian Dollar / Japanese Yen',
    type: 'forex',
    currentPrice: 101.52,
    priceChange: 0.24,
    priceChangePercent: 0.24,
    market: 'OTC',
  },
];

// Exotic forex pairs
export const exoticForexPairs: Asset[] = [
  {
    symbol: 'USD/SEK',
    name: 'US Dollar / Swedish Krona',
    type: 'forex',
    currentPrice: 10.3267,
    priceChange: -0.0187,
    priceChangePercent: -0.18,
    market: 'OTC',
  },
  {
    symbol: 'USD/DKK',
    name: 'US Dollar / Danish Krone',
    type: 'forex',
    currentPrice: 6.8432,
    priceChange: -0.0142,
    priceChangePercent: -0.21,
    market: 'OTC',
  },
  {
    symbol: 'USD/NOK',
    name: 'US Dollar / Norwegian Krone',
    type: 'forex',
    currentPrice: 10.6529,
    priceChange: -0.0237,
    priceChangePercent: -0.22,
    market: 'OTC',
  },
  {
    symbol: 'USD/RON',
    name: 'US Dollar / Romanian Leu',
    type: 'forex',
    currentPrice: 4.6821,
    priceChange: -0.0073,
    priceChangePercent: -0.16,
    market: 'OTC',
  },
  {
    symbol: 'EUR/RON',
    name: 'Euro / Romanian Leu',
    type: 'forex',
    currentPrice: 5.0764,
    priceChange: -0.0082,
    priceChangePercent: -0.16,
    market: 'OTC',
  },
  {
    symbol: 'GBP/RON',
    name: 'British Pound / Romanian Leu',
    type: 'forex',
    currentPrice: 5.8742,
    priceChange: 0.0123,
    priceChangePercent: 0.21,
    market: 'OTC',
  },
  {
    symbol: 'USD/PLN',
    name: 'US Dollar / Polish Zloty',
    type: 'forex',
    currentPrice: 3.9854,
    priceChange: -0.0087,
    priceChangePercent: -0.22,
    market: 'OTC',
  },
  {
    symbol: 'USD/HUF',
    name: 'US Dollar / Hungarian Forint',
    type: 'forex',
    currentPrice: 358.64,
    priceChange: -0.76,
    priceChangePercent: -0.21,
    market: 'OTC',
  },
  {
    symbol: 'USD/TRY',
    name: 'US Dollar / Turkish Lira',
    type: 'forex',
    currentPrice: 32.8734,
    priceChange: 0.0432,
    priceChangePercent: 0.13,
    market: 'OTC',
  },
  {
    symbol: 'USD/ZAR',
    name: 'US Dollar / South African Rand',
    type: 'forex',
    currentPrice: 18.4267,
    priceChange: 0.0342,
    priceChangePercent: 0.19,
    market: 'OTC',
  },
];

// Emerging market forex pairs
export const emergingMarketForexPairs: Asset[] = [
  {
    symbol: 'USD/MXN',
    name: 'US Dollar / Mexican Peso',
    type: 'forex',
    currentPrice: 16.9842,
    priceChange: -0.0321,
    priceChangePercent: -0.19,
    market: 'OTC',
  },
  {
    symbol: 'USD/BRL',
    name: 'US Dollar / Brazilian Real',
    type: 'forex',
    currentPrice: 5.1437,
    priceChange: 0.0087,
    priceChangePercent: 0.17,
    market: 'OTC',
  },
  {
    symbol: 'USD/INR',
    name: 'US Dollar / Indian Rupee',
    type: 'forex',
    currentPrice: 83.7621,
    priceChange: 0.0432,
    priceChangePercent: 0.05,
    market: 'OTC',
  },
  {
    symbol: 'USD/CNY',
    name: 'US Dollar / Chinese Yuan',
    type: 'forex',
    currentPrice: 7.2345,
    priceChange: 0.0032,
    priceChangePercent: 0.04,
    market: 'OTC',
  },
  {
    symbol: 'USD/HKD',
    name: 'US Dollar / Hong Kong Dollar',
    type: 'forex',
    currentPrice: 7.8196,
    priceChange: 0.0023,
    priceChangePercent: 0.03,
    market: 'OTC',
  },
  {
    symbol: 'USD/SGD',
    name: 'US Dollar / Singapore Dollar',
    type: 'forex',
    currentPrice: 1.3452,
    priceChange: -0.0021,
    priceChangePercent: -0.16,
    market: 'OTC',
  },
  {
    symbol: 'USD/TWD',
    name: 'US Dollar / Taiwan Dollar',
    type: 'forex',
    currentPrice: 32.1432,
    priceChange: -0.0321,
    priceChangePercent: -0.10,
    market: 'OTC',
  },
  {
    symbol: 'USD/KRW',
    name: 'US Dollar / South Korean Won',
    type: 'forex',
    currentPrice: 1345.76,
    priceChange: -2.13,
    priceChangePercent: -0.16,
    market: 'OTC',
  },
  {
    symbol: 'USD/AED',
    name: 'US Dollar / UAE Dirham',
    type: 'forex',
    currentPrice: 3.6731,
    priceChange: 0.0001,
    priceChangePercent: 0.00,
    market: 'OTC',
  },
  {
    symbol: 'USD/SAR',
    name: 'US Dollar / Saudi Riyal',
    type: 'forex',
    currentPrice: 3.7502,
    priceChange: 0.0001,
    priceChangePercent: 0.00,
    market: 'OTC',
  },
  {
    symbol: 'USD/ILS',
    name: 'US Dollar / Israeli Shekel',
    type: 'forex',
    currentPrice: 3.7123,
    priceChange: -0.0087,
    priceChangePercent: -0.23,
    market: 'OTC',
  },
  {
    symbol: 'USD/RUB',
    name: 'US Dollar / Russian Ruble',
    type: 'forex',
    currentPrice: 92.8642,
    priceChange: 0.1324,
    priceChangePercent: 0.14,
    market: 'OTC',
  },
];
