
import { Asset } from "../types/asset-types";

// European Stocks
export const europeanStocks: Asset[] = [
  {
    symbol: 'ASML',
    name: 'ASML Holding N.V.',
    type: 'stock',
    currentPrice: 905.42,
    priceChange: 12.34,
    priceChangePercent: 1.38,
    market: 'OTC',
  },
  {
    symbol: 'SAP',
    name: 'SAP SE',
    type: 'stock',
    currentPrice: 178.95,
    priceChange: 1.23,
    priceChangePercent: 0.69,
    market: 'OTC',
  },
  {
    symbol: 'SIEGY',
    name: 'Siemens AG',
    type: 'stock',
    currentPrice: 89.76,
    priceChange: 0.54,
    priceChangePercent: 0.61,
    market: 'OTC',
  },
  {
    symbol: 'NSRGY',
    name: 'Nestlé S.A.',
    type: 'stock',
    currentPrice: 121.54,
    priceChange: -0.42,
    priceChangePercent: -0.34,
    market: 'OTC',
  },
  {
    symbol: 'RHHBY',
    name: 'Roche Holding AG',
    type: 'stock',
    currentPrice: 35.67,
    priceChange: 0.21,
    priceChangePercent: 0.59,
    market: 'OTC',
  },
  {
    symbol: 'LVMUY',
    name: 'LVMH Moët Hennessy - Louis Vuitton',
    type: 'stock',
    currentPrice: 156.78,
    priceChange: 2.31,
    priceChangePercent: 1.50,
    market: 'OTC',
  },
  {
    symbol: 'TTE',
    name: 'TotalEnergies SE',
    type: 'stock',
    currentPrice: 65.32,
    priceChange: 0.87,
    priceChangePercent: 1.35,
    market: 'OTC',
  },
  {
    symbol: 'SHELLF',
    name: 'Shell plc',
    type: 'stock',
    currentPrice: 32.45,
    priceChange: 0.34,
    priceChangePercent: 1.06,
    market: 'OTC',
  },
];

// Asian Stocks
export const asianStocks: Asset[] = [
  {
    symbol: 'BABA',
    name: 'Alibaba Group Holding Limited',
    type: 'stock',
    currentPrice: 76.45,
    priceChange: 1.23,
    priceChangePercent: 1.64,
    market: 'OTC',
  },
  {
    symbol: 'TCEHY',
    name: 'Tencent Holdings Limited',
    type: 'stock',
    currentPrice: 45.32,
    priceChange: 0.87,
    priceChangePercent: 1.96,
    market: 'OTC',
  },
  {
    symbol: 'TSM',
    name: 'Taiwan Semiconductor Manufacturing Company Limited',
    type: 'stock',
    currentPrice: 143.67,
    priceChange: 2.31,
    priceChangePercent: 1.63,
    market: 'OTC',
  },
  {
    symbol: '9984.T',
    name: 'SoftBank Group Corp.',
    type: 'stock',
    currentPrice: 7345.00,
    priceChange: 45.00,
    priceChangePercent: 0.62,
    market: 'OTC',
  },
  {
    symbol: '7974.T',
    name: 'Nintendo Co., Ltd.',
    type: 'stock',
    currentPrice: 7450.00,
    priceChange: 120.00,
    priceChangePercent: 1.64,
    market: 'OTC',
  },
  {
    symbol: '6758.T',
    name: 'Sony Group Corporation',
    type: 'stock',
    currentPrice: 12450.00,
    priceChange: 145.00,
    priceChangePercent: 1.18,
    market: 'OTC',
  },
];
