
import { Asset } from "../types/asset-types";

// US Tech Stocks
export const techStocks: Asset[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    type: 'stock',
    currentPrice: 187.65,
    priceChange: 1.23,
    priceChangePercent: 0.66,
    market: 'NASDAQ',
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    type: 'stock',
    currentPrice: 402.12,
    priceChange: -3.45,
    priceChangePercent: -0.85,
    market: 'NASDAQ',
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    type: 'stock',
    currentPrice: 156.09,
    priceChange: 2.75,
    priceChangePercent: 1.79,
    market: 'NASDAQ',
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    type: 'stock',
    currentPrice: 178.92,
    priceChange: -0.87,
    priceChangePercent: -0.48,
    market: 'NASDAQ',
  },
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    type: 'stock',
    currentPrice: 177.50,
    priceChange: 5.32,
    priceChangePercent: 3.09,
    market: 'NASDAQ',
  },
  {
    symbol: 'META',
    name: 'Meta Platforms, Inc.',
    type: 'stock',
    currentPrice: 486.18,
    priceChange: 4.27,
    priceChangePercent: 0.89,
    market: 'NASDAQ',
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    type: 'stock',
    currentPrice: 105.72,
    priceChange: 2.34,
    priceChangePercent: 2.26,
    market: 'NASDAQ',
  },
  {
    symbol: 'NFLX',
    name: 'Netflix, Inc.',
    type: 'stock',
    currentPrice: 632.41,
    priceChange: 8.92,
    priceChangePercent: 1.43,
    market: 'NASDAQ',
  },
  {
    symbol: 'INTC',
    name: 'Intel Corporation',
    type: 'stock',
    currentPrice: 35.21,
    priceChange: -0.42,
    priceChangePercent: -1.18,
    market: 'NASDAQ',
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices, Inc.',
    type: 'stock',
    currentPrice: 156.82,
    priceChange: 3.76,
    priceChangePercent: 2.46,
    market: 'NASDAQ',
  },
  {
    symbol: 'CRM',
    name: 'Salesforce, Inc.',
    type: 'stock',
    currentPrice: 275.44,
    priceChange: 1.91,
    priceChangePercent: 0.70,
    market: 'NYSE',
  },
  {
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    type: 'stock',
    currentPrice: 486.31,
    priceChange: -2.34,
    priceChangePercent: -0.48,
    market: 'NASDAQ',
  },
  {
    symbol: 'PYPL',
    name: 'PayPal Holdings, Inc.',
    type: 'stock',
    currentPrice: 62.87,
    priceChange: 0.45,
    priceChangePercent: 0.72,
    market: 'NASDAQ',
  },
  {
    symbol: 'CSCO',
    name: 'Cisco Systems, Inc.',
    type: 'stock',
    currentPrice: 49.87,
    priceChange: -0.13,
    priceChangePercent: -0.26,
    market: 'NASDAQ',
  },
];

// Modern tech companies
export const modernTechStocks: Asset[] = [
  {
    symbol: 'ZM',
    name: 'Zoom Video Communications, Inc.',
    type: 'stock',
    currentPrice: 61.45,
    priceChange: -0.87,
    priceChangePercent: -1.40,
    market: 'NASDAQ',
  },
  {
    symbol: 'ABNB',
    name: 'Airbnb, Inc.',
    type: 'stock',
    currentPrice: 144.32,
    priceChange: 2.43,
    priceChangePercent: 1.71,
    market: 'NASDAQ',
  },
  {
    symbol: 'DASH',
    name: 'DoorDash, Inc.',
    type: 'stock',
    currentPrice: 118.76,
    priceChange: 1.34,
    priceChangePercent: 1.14,
    market: 'NASDAQ',
  },
  {
    symbol: 'U',
    name: 'Unity Software Inc.',
    type: 'stock',
    currentPrice: 19.43,
    priceChange: -0.54,
    priceChangePercent: -2.71,
    market: 'NASDAQ',
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies Inc.',
    type: 'stock',
    currentPrice: 23.87,
    priceChange: 0.87,
    priceChangePercent: 3.78,
    market: 'NASDAQ',
  },
  {
    symbol: 'SNOW',
    name: 'Snowflake Inc.',
    type: 'stock',
    currentPrice: 152.76,
    priceChange: 2.31,
    priceChangePercent: 1.53,
    market: 'NASDAQ',
  },
  {
    symbol: 'CRWD',
    name: 'CrowdStrike Holdings, Inc.',
    type: 'stock',
    currentPrice: 321.54,
    priceChange: 4.76,
    priceChangePercent: 1.50,
    market: 'NASDAQ',
  },
  {
    symbol: 'OKTA',
    name: 'Okta, Inc.',
    type: 'stock',
    currentPrice: 91.45,
    priceChange: 1.23,
    priceChangePercent: 1.36,
    market: 'NASDAQ',
  },
  {
    symbol: 'SHOP',
    name: 'Shopify Inc.',
    type: 'stock',
    currentPrice: 76.89,
    priceChange: 1.45,
    priceChangePercent: 1.92,
    market: 'NASDAQ',
  },
  {
    symbol: 'SQ',
    name: 'Block, Inc.',
    type: 'stock',
    currentPrice: 67.43,
    priceChange: 1.87,
    priceChangePercent: 2.85,
    market: 'NASDAQ',
  },
  {
    symbol: 'UBER',
    name: 'Uber Technologies, Inc.',
    type: 'stock',
    currentPrice: 65.37,
    priceChange: 0.45,
    priceChangePercent: 0.69,
    market: 'NASDAQ',
  },
  {
    symbol: 'LYFT',
    name: 'Lyft, Inc.',
    type: 'stock',
    currentPrice: 17.32,
    priceChange: 0.21,
    priceChangePercent: 1.23,
    market: 'NASDAQ',
  },
];

// Cloud/Enterprise tech stocks
export const enterpriseTechStocks: Asset[] = [
  {
    symbol: 'ORCL',
    name: 'Oracle Corporation',
    type: 'stock',
    currentPrice: 125.76,
    priceChange: 0.87,
    priceChangePercent: 0.70,
    market: 'NASDAQ',
  },
  {
    symbol: 'IBM',
    name: 'International Business Machines Corporation',
    type: 'stock',
    currentPrice: 188.62,
    priceChange: 1.24,
    priceChangePercent: 0.66,
    market: 'NYSE',
  },
  {
    symbol: 'DDOG',
    name: 'Datadog, Inc.',
    type: 'stock',
    currentPrice: 117.45,
    priceChange: 2.34,
    priceChangePercent: 2.03,
    market: 'NASDAQ',
  },
  {
    symbol: 'NET',
    name: 'Cloudflare, Inc.',
    type: 'stock',
    currentPrice: 87.34,
    priceChange: 1.87,
    priceChangePercent: 2.19,
    market: 'NASDAQ',
  },
  {
    symbol: 'TEAM',
    name: 'Atlassian Corporation',
    type: 'stock',
    currentPrice: 172.56,
    priceChange: 3.45,
    priceChangePercent: 2.04,
    market: 'NASDAQ',
  },
  {
    symbol: 'ZS',
    name: 'Zscaler, Inc.',
    type: 'stock',
    currentPrice: 184.76,
    priceChange: 4.23,
    priceChangePercent: 2.34,
    market: 'NASDAQ',
  },
  {
    symbol: 'TTD',
    name: 'The Trade Desk, Inc.',
    type: 'stock',
    currentPrice: 91.43,
    priceChange: 1.23,
    priceChangePercent: 1.36,
    market: 'NASDAQ',
  },
  {
    symbol: 'ROKU',
    name: 'Roku, Inc.',
    type: 'stock',
    currentPrice: 62.78,
    priceChange: 1.54,
    priceChangePercent: 2.51,
    market: 'NASDAQ',
  },
  {
    symbol: 'PINS',
    name: 'Pinterest, Inc.',
    type: 'stock',
    currentPrice: 33.45,
    priceChange: 0.32,
    priceChangePercent: 0.97,
    market: 'NASDAQ',
  },
  {
    symbol: 'SNAP',
    name: 'Snap Inc.',
    type: 'stock',
    currentPrice: 14.76,
    priceChange: 0.23,
    priceChangePercent: 1.58,
    market: 'NASDAQ',
  },
  {
    symbol: 'RBLX',
    name: 'Roblox Corporation',
    type: 'stock',
    currentPrice: 41.23,
    priceChange: 0.87,
    priceChangePercent: 2.16,
    market: 'NASDAQ',
  },
  {
    symbol: 'COIN',
    name: 'Coinbase Global, Inc.',
    type: 'stock',
    currentPrice: 178.43,
    priceChange: 5.32,
    priceChangePercent: 3.07,
    market: 'NASDAQ',
  },
  {
    symbol: 'AI',
    name: 'C3.ai, Inc.',
    type: 'stock',
    currentPrice: 28.24,
    priceChange: 0.87,
    priceChangePercent: 3.18,
    market: 'NASDAQ',
  },
];
