
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrcrsyuuydixfjwaaoxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyY3JzeXV1eWRpeGZqd2Fhb3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjQwNjIsImV4cCI6MjA2MjcwMDA2Mn0.bt-AHFC5WjLThgzHhkpQfeOZKp91ulR8euSnHpVs7rE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // Use localStorage for session persistence
    persistSession: true,
    autoRefreshToken: true,
  },
});
